# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: free_range/core/client/tests/test_rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='free_range/core/client/tests/test_rpc.proto',
  package='free_range.client.tests.papi',
  syntax='proto3',
  serialized_pb=_b('\n+free_range/core/client/tests/test_rpc.proto\x12\x1c\x66ree_range.client.tests.papi\"!\n\x0eTestRpcRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"#\n\x0fTestRpcResponse\x12\x10\n\x08response\x18\x01 \x01(\tb\x06proto3')
)




_TESTRPCREQUEST = _descriptor.Descriptor(
  name='TestRpcRequest',
  full_name='free_range.client.tests.papi.TestRpcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='free_range.client.tests.papi.TestRpcRequest.request', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=110,
)


_TESTRPCRESPONSE = _descriptor.Descriptor(
  name='TestRpcResponse',
  full_name='free_range.client.tests.papi.TestRpcResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='free_range.client.tests.papi.TestRpcResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=147,
)

DESCRIPTOR.message_types_by_name['TestRpcRequest'] = _TESTRPCREQUEST
DESCRIPTOR.message_types_by_name['TestRpcResponse'] = _TESTRPCRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestRpcRequest = _reflection.GeneratedProtocolMessageType('TestRpcRequest', (_message.Message,), dict(
  DESCRIPTOR = _TESTRPCREQUEST,
  __module__ = 'free_range.core.client.tests.test_rpc_pb2'
  # @@protoc_insertion_point(class_scope:free_range.client.tests.papi.TestRpcRequest)
  ))
_sym_db.RegisterMessage(TestRpcRequest)

TestRpcResponse = _reflection.GeneratedProtocolMessageType('TestRpcResponse', (_message.Message,), dict(
  DESCRIPTOR = _TESTRPCRESPONSE,
  __module__ = 'free_range.core.client.tests.test_rpc_pb2'
  # @@protoc_insertion_point(class_scope:free_range.client.tests.papi.TestRpcResponse)
  ))
_sym_db.RegisterMessage(TestRpcResponse)


# @@protoc_insertion_point(module_scope)
